### ISSUE TITLE
is bootstrap dependency necessary ?

### ISSUE THREAD

**Issue by msio** [SchweizerischeBundesbahnen/esta-webjs-extensions#56]
https://github.com/SchweizerischeBundesbahnen/esta-webjs-extensions/blob/d18b12d165bc63faecde1a0023d28e228724d4ab/package.json#L25

**Comment by kyubisation** [comment]
It is necessary for the styles found in projects/esta-webjs-extensions/src/styles. But maybe in a future release we'll move them into another package or into the project template.
