### ISSUE TITLE
adfs_sbb_prod wird eingestellt

### ISSUE THREAD

**Issue by Masterxilo** [SchweizerischeBundesbahnen/esta-webjs-extensions#62]
@kreuzerk @ReToCode 

https://github.com/SchweizerischeBundesbahnen/esta-webjs-extensions/blob/master/projects/esta-webjs-extensions/src/lib/auth/auth.module.ts

verweist auf
adfs_sbb_prod
der wird aber eingestellt, man sollte azure_sbb_prod verwenden,
siehe
https://confluence.sbb.ch/pages/viewpage.action?pageId=862880181

lg
Paul

**Comment by kyubisation** [comment]
Will be tracked in SchweizerischeBundesbahnen/sbb-angular#97
