### ISSUE TITLE
Überschreiben von loginOptions und idpHint

### ISSUE THREAD

**Issue by Masterxilo** [SchweizerischeBundesbahnen/esta-webjs-extensions#63]
Die Art wie der default Wert für KeycloakLoginOptions hier definiert wird:

https://github.com/SchweizerischeBundesbahnen/esta-webjs-extensions/blob/master/projects/esta-webjs-extensions/src/lib/auth/auth.module.ts

Ist nicht kompatibel mit der Empfehlung wie man das auth.module.js verwenden soll:

https://confluence.sbb.ch/display/ESTA/Authentifizierungsmodul

Man muss in der Methode "AuthModule.forRoot" noch den 3. Parameter KeycloakLoginOptions  Angeben und dort den idpHint setzen - denn obwohl das KeycloakConfig Objekt auch einen idpHint hat wird der offenbar (wegen diesen expliziten Login options?) ignoriert.

Deshalb sieht mein environment File jetzt so aus:

```
const keycloakInitOptions: KeycloakInitOptions = {
  flow: 'standard'
};
const keycloakConfig: KeycloakConfig = {
  realm: 'SBB_Public',
  url: 'https://sso-int.sbb.ch/auth',
  clientId: 'client-***-dev',
  // ***-526 adfs -> azure IdP https://confluence.sbb.ch/pages/viewpage.action?pageId=862880181
  idpHint: 'azure_sbb_prod'
};
// SEI-526 adfs -> azure IdP https://confluence.sbb.ch/pages/viewpage.action?pageId=862880181
const keycloakLoginOptions: KeycloakLoginOptions = {
  idpHint: 'azure_sbb_prod'
};

export const environment = {
  environment: 'dev',
  resourceServerUrl: 'https://***,
  version: require('../../package.json').version,
  authConfigServiceId: 'service-***-dev',
  authConfig: keycloakConfig,
  authOptions: keycloakInitOptions,
  authLoginOptions: keycloakLoginOptions,
};
```

und mein .forRoot so
```
AuthModule.forRoot(environment.authConfig, environment.authOptions, environment.authLoginOptions),
```

erst so klappt für mich der Wechsel auf azure_sbb_prod statt adfs_sbb_prod, vgl. https://github.com/SchweizerischeBundesbahnen/esta-webjs-extensions/issues/62

**Comment by kyubisation** [comment]
Wird teilweise in SchweizerischeBundesbahnen/sbb-angular#98 behandelt.
Dokumentation werde ich anpassen.
